services:
  - type: web
    name: 0-0htg-80-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: PORT
        value: 8080
      - key: SOFASCORE_PROXY_BASE
        value: https://api.sofascore.com/api/v1

